### ISSUE TITLE
ttl is not able to be set.

### ISSUE THREAD

**Issue by dalgrim** [jmrplens/DynDNS_Cloudflare_IPv4-6#74]
TTL  gives an error if any number is entered and forces back to auto when the script is run.

Error message received:
Error! 'ttl' out of range (120-7200) or not set to 'auto'. Force set to 'auto'

Config from the .yaml:
domains:
  - name: subdomain.domain.com (<-- It is correct in the actual config file, changed here for obvious reasons)
    ip_type: external
    ipv4: true
    ipv6: true
    proxied: false
    ttl: 600

**Comment by dalgrim** [comment]
I think the error is here:
```
  # Check validity of "ttl" parameter
    if [ "${domains__ttl[i]}" -lt 120 ] 2>/dev/null ||
      [ "${domains__ttl[i]}" -gt 7200 ] 2>/dev/null ||
      [ "${domains__ttl[i]}" != "auto" ]; then
      warn_msg "Error! 'ttl' out of range (120-7200) or not set to 'auto'. Force set to '$def_ttl'"
      def_ttl_enabled[i]=true
    else
      def_ttl_enabled[i]=false
    fi
```
----------------
Based on this, If the number is less than 120, greater than 7200, or not Auto it will force to auto. Based on the last "!= auto" this will force anything not auto to auto. As it's a chained OR statement it will always fail because if it's a number it can't be auto, and if it's auto it can't be between 120 and 7200.

It should probably be a check for IF check for "auto", then IF NOT "auto" an IF OR on the values between 120 and 7200. 

Also the 2>/dev/null is just suppressing the error that's being generated because it can not compare a string to a number in a [] with -lt or -gt you'd need [[ ]] which is bash specific.

**Comment by dalgrim** [comment]
I did manage to get the TTL working. I'm not a Bash expert so I had to use another temporary variable to make it work. I'm sure there is a way to do it with one of the ten different Bash's bracket/parentheses combos...
Near line 290 of the .sh file change the following:
```
    # Check validity of "ttl" parameter
    if [ "${domains__ttl[i]}" -lt 120 ] 2>/dev/null ||
      [ "${domains__ttl[i]}" -gt 7200 ] 2>/dev/null ||
      [ "${domains__ttl[i]}" != "auto" ]; then
      warn_msg "Error! 'ttl' out of range (120-7200) or not set to 'auto'. Force set to '$def_ttl'"
      def_ttl_enabled[i]=true
    else
      def_ttl_enabled[i]=false
    fi
``` 
to
   ```
    # Check validity of "ttl" parameter
    dom_ttl = ${domain__ttl[i]}
    if [ $"dom_ttl" != "auto" ]; then
        # TTL is not auto in the config so check if the values are valid between 120 and 7200
        if [ "$dom_ttl" -lt 120 || "$dom_ttl" -gt 7200 ]; then
            # invalid value was found so force the default and give a warning message
            warn_msg "Error! 'ttl' out of range (120-7200) or not set to 'auto'. Force set to '$def_ttl'"
            def_ttl_enabled[i]=true
        else
            # Valid values were found so allow them and disable the default
            def_ttl_enabled[i]=false
        fi
    else
        # TTL was set to auto in the config
        def_ttl_enabled[i]=false
    fi
    unset dom_ttl
```

**Comment by dalgrim** [comment]
Here is the fix for the problem. I'm sure there is a way to do this without the extra variable but shell scripting parenthesis are not my thing. [] [[]] () (()) {} all do different things...

At line 290 in the script file change:
```
    # Check validity of "ttl" parameter
    if [ "${domains__ttl[i]}" -lt 120 ] 2>/dev/null ||
      [ "${domains__ttl[i]}" -gt 7200 ] 2>/dev/null ||
      [ "${domains__ttl[i]}" != "auto" ]; then
      warn_msg "Error! 'ttl' out of range (120-7200) or not set to 'auto'. Force set to '$def_ttl'"
      def_ttl_enabled[i]=true
    else
      def_ttl_enabled[i]=false
    fi
```
to
```
    # Check validity of "ttl" parameter
    dom_ttl=${domains__ttl[i]}
    if [ "$dom_ttl" != "auto" ]; then
        # TTL is not auto in the config so check if the values are valid between 120 and 7200
        if [ "$dom_ttl" -lt 120 ] || [ "$dom_ttl" -gt 7200 ]; then
            # invalid value was found so force the default and give a warning message
            warn_msg "Error! 'ttl' out of range (120-7200) or not set to 'auto'. Force set to '$def_ttl'"
            def_ttl_enabled[i]=true
        else
            # Valid values were found so allow them and disable the default
            def_ttl_enabled[i]=false
        fi
    else
        # TTL was set to auto in the config
        def_ttl_enabled[i]=false
    fi
    unset dom_ttl
```

I hope this helps

**Comment by jmrplens** [comment]
Holy shit, I hadn't seen this issue, I'm very sorry for the delay, I'm going to review the implementation of @Mikkel-Coder and merge it

Thanks!
